name: Simple Github Actions 
on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Simple echo of a given input string
        run: echo "This is the first github actions workflow file"
      - name: To print the IP of the runner
        run: |
            ifconfig
            echo "-------------"
            ifconfig | grep inet
            echo "-------------"
            ping -c 2 172.17.0.1
